### ISSUE TITLE
Pretrained embeddings for more languages?

### ISSUE THREAD

**Issue by EmilStenstrom** [wikipedia2vec/wikipedia2vec#14]
Hi 👋 
This library really does look fantastic! I really appreciate the list of pre-trained embeddings that can be downloaded.

Before doing the tutorial for creating embeddings for the language I’m looking for... Would you consider adding more pre-trainer languages? I’m specifically looking for Swedish, which seems not part of your top 10 list.

**Comment by ikuyamada** [comment]
Thank you for your comment.
However, we don't currently have a plan to add languages for our pretrained embeddings.
Please obtain the corresponding Wikipedia dump and run the training on your machine! 👍

**Comment by ypc-stu** [comment]
Thank you for sharing codes. I have a question:
I downloaded the pre-trained embeddings from  https://wikipedia2vec.github.io/wikipedia2vec/pretrained/
Is the entity pre-trained embeddings extracted from Wikipedia ?

**Comment by ikuyamada** [comment]
Yes, these entity embeddings were trained on Wikipedia.

**Comment by ypc-stu** [comment]
Thanks for your answers.
