### ISSUE TITLE
Debiased embeddings?

### ISSUE THREAD

**Issue by EmilStenstrom** [wikipedia2vec/wikipedia2vec#15]
Seems it’s rather easy to remove (a part of) gender biases from embeddings. Is this something you would consider?

Man is to Computer Programmer as Woman is to Homemaker: https://papers.nips.cc/paper/6228-man-is-to-computer-programmer-as-woman-is-to-homemaker-debiasing-word-embeddings.pdf

**Comment by ikuyamada** [comment]
The paper proposes an interesting method though, we will not implement this in the near future.
But since the learned embeddings can be loaded using other word embedding libraries (e.g., gensim), you can easily apply an existing implementation of this method to the learned word embeddings.
