### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by EternalMoment** [wikipedia2vec/wikipedia2vec#18]
The [Visualization](http://projector.tensorflow.org/?config=https://wikipedia2vec.github.io/projector_files/config.json)  tab on the [website](https://wikipedia2vec.github.io/wikipedia2vec/) is broken.

**Comment by ikuyamada** [comment]
Thank you for reporting the issue! However, the link works properly in my browser (Google Chrome). The visualization page is based on Tensorflow Projector which is based fully on JavaScript,  this issue may be an issue of Tensorflow Projector.
It would be appreciated if you let me know the details of your browser.

**Comment by EternalMoment** [comment]
It works today. I was using Chrome as well. Maybe something’s wrong with my network. Let me close it.
