### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

### ISSUE THREAD

**Issue by EmilStenstrom** [wikipedia2vec/wikipedia2vec#19]
Hi,

I'm trying to run wikipedia2vec on Python 3.7, on Windows 10, but I get problems with "numpy.ufunc has the wrong size". 

Googling this points to errors with multiple versions of numpy installed, but I have verified that this is not the case. I'm executing this inside a separate virtualenv, and pip freeze shows only the latest version of numpy installed. I've also tried first installing numpy, and then wikipedia2vec.

The reason I think this might have something to do with wikipedia2vec, is the strange path at the end of the stacktrace: ".venv/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd". This is NOT the version of python I have installed, or a path that exists on my filesystem at all (I don't even have a .venv directory!). The only reference to this directory is inside a wikipedia2vec.cpp file, which somehow is created while wikipedia2vec is creates.

I do not get these errors on Python3.7 in MacOSX when I tried it there.

```
(wikipedia-embeddings) C:\Projects\wikipedia-embeddings>wikipedia2vec build-dump-db svwiki-latest-pages-articles.xml.bz2 svwiki-dump-db.bin
Traceback (most recent call last):
  File "c:\program files\python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Envs\wikipedia-embeddings\Scripts\wikipedia2vec.exe\__main__.py", line 5, in <module>
  File "c:\users\admin\envs\wikipedia-embeddings\lib\site-packages\wikipedia2vec\__init__.py", line 4, in <module>
    from .dictionary import Dictionary
  File ".venv/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd", line 872, in init wikipedia2vec.dictionary
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

Any ideas of what I should try next?

```
(wikipedia-embeddings) C:\Projects\wikipedia-embeddings>pip freeze
Click==7.0
jieba==0.39
joblib==0.13.0
lmdb==0.94
marisa-trie==0.7.5
mwparserfromhell==0.5.2
numpy==1.15.4
scipy==1.2.0
six==1.12.0
tqdm==4.28.1
wikipedia2vec==1.0.1
```

**Comment by EmilStenstrom** [comment]
I've already tried all these things.

- I've recreated my virtualenv from scratch 3 times. Same result every time.
- I've tried first installing numpy, and then installing wikipedia2vec, no difference.
- I've tried both settings --no-cache-dir and manually clearing pip's cache directory
- I've read the two issues you link to, and tried to find hints on what's wrong from there. No luck.

**Comment by ikuyamada** [comment]
I am sorry for the delayed reply.
I tried to install WIkipedia2Vec using Python 3.7.2, virtualenv, and Windows Server 2016, and successfully installed it without any problems.
If you have time, please install this software directly from the git repository using the following instructions:
[https://wikipedia2vec.github.io/wikipedia2vec/install/](https://wikipedia2vec.github.io/wikipedia2vec/install/)

**Comment by EmilStenstrom** [comment]
@ikuyamada Thanks again for taking the time to troubleshoot this! That you can install it confirms that this is a problem on my side. I'll investigate further and report back here if I make any progress.

**Comment by RoelVdP** [comment]
@EmilStenstrom did you find out what it was?

**Comment by EmilStenstrom** [comment]
@RoelVdP: Not exactly. I tried clearing my environment in a could of more ways, and then it suddenly worked. So an incorrect numpy version that interfered somehow.
