### ISSUE TITLE
how to load model with gensim?

### ISSUE THREAD

**Issue by eumenide** [wikipedia2vec/wikipedia2vec#20]
Hi,

I have downloaded the [pretrained embedding model](http://wikipedia2vec.s3.amazonaws.com/models/en/2018-04-20/enwiki_20180420_100d.pkl.bz2), and I loaded the file using Gensim's `load_word2vec_format()`. However, it failed and given the following error:
```python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

So how can I correctly load the pretrained model using gensim? Can you help me？

Thanks

**Comment by ikuyamada** [comment]
Hi,
You need to use the [text file](http://wikipedia2vec.s3.amazonaws.com/models/en/2018-04-20/enwiki_20180420_100d.txt.bz2) rather than the binary file.
Note that it is required to decompress the file before using it.

**Comment by eumenide** [comment]
Hi @ikuyamada ,
Thank you for your solution and it works.
And it works successfully without decompressing the text file.
