### ISSUE TITLE
Number of pre-trained embeddings questions

### ISSUE THREAD

**Issue by andrejzg** [wikipedia2vec/wikipedia2vec#21]
I downloaded the English pre-trained embeddings _enwiki__20180420_ from your [website](https://wikipedia2vec.github.io/wikipedia2vec/pretrained/) and found there to be **2,592,608** entities. 

For roughly the same period (2018-01-01), the [size of wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Size_of_Wikipedia) page quotes **5,541,900** articles. 

Do you know why the discrepancy? 

Thanks!

**Comment by ikuyamada** [comment]
The pretrained model does not include entities that appear as links in Wikipedia less than 5 times. You can change this behavior by setting *--min-entity-count* option.

**Comment by EternalMoment** [comment]
Hey @ikuyamada,

I'm working on a research using wikipedia2vec embedding, and want to check the coverage of it. I'm also using the AIDA dataset sited in your paper. 

I found 222 unique entities missing from the released pre-trained wikipedia2vec model.

Here are some examples:
The first column is the number char in its page
The second column is the number of outgoing link in its page
The third column is the entity's Wikipedia link from AIDA dataset
```
(6380, 63, 'http://en.wikipedia.org/wiki/Stephanie_Storp')
(5999, 68, 'http://en.wikipedia.org/wiki/Kurt_Betschart')
(4382, 24, 'http://en.wikipedia.org/wiki/Middle_East_Economic_Survey')
(4119, 41, 'http://en.wikipedia.org/wiki/Lucy_Tyler-Sharman')
(3292, 44, 'http://en.wikipedia.org/wiki/Randy_Jones_(bobsleigh)')
(3262, 35, 'http://en.wikipedia.org/wiki/Wendy_Everson')
(3175, 50, 'http://en.wikipedia.org/wiki/James_Heath_(Boxer)')
(3064, 63, 'http://en.wikipedia.org/wiki/Mark_Rutherford_(footballer)')
(2936, 29, 'http://en.wikipedia.org/wiki/Gunther_Schepens')
...
```
I have eliminated the case where such entity `is_disambiguation` page, and ones that does not have a Wikipedia page in dump db. Therefore, the 222 ones 
1. are not disambiguation page 
2. have Wikipedia page description

Please correct me if I'm wrong, but the only reason why it does not get included in the trained embedding is probably that the entity does not meet the threshold of 
1. min-paragraph-len
2. min-entity-count

During model training, such missing data points could be ignored. As for evaluation of AIDA A (dev) and AIDA B (test), how do you handle these missing data points?
