### ISSUE TITLE
Chinese words segment

### ISSUE THREAD

**Issue by Jackie127** [wikipedia2vec/wikipedia2vec#24]
Which python packages you use to complete the Chinese words segmentation?

**Comment by ikuyamada** [comment]
Jieba is currently used to segment Chinese words.

**Comment by Jackie127** [comment]
which script  includes the jieba package to complete segmentation?

**Comment by ikuyamada** [comment]
This script imports jieba to tokenize Chinese texts:
https://github.com/wikipedia2vec/wikipedia2vec/blob/master/wikipedia2vec/utils/tokenizer/jieba_tokenizer.pyx

**Comment by Jackie127** [comment]
if the Chinese corpus has completed the segmentation  before using the wikipedia2vec to train word embedding,how to stop using  jieba to complete segmentation?

**Comment by ikuyamada** [comment]
Wikipedia2Vec is developed for training embeddings directly from a Wikipedia dump. Therefore, this tool does not support arbitrary input corpus other than Wikipedia dump.

**Comment by Jackie127** [comment]
the Chinese corpus's format is .xml.bz2 like wikipedia, the word in sentence is split by ' ' like '今天 天气 不错' rather than '今天天气不错'。

**Comment by ikuyamada** [comment]
This format is not supported by this tool.
