### ISSUE TITLE
Delete the token '\n' (and '\r' if any) in the txt format.

### ISSUE THREAD

**Issue by cloudyyyyy** [wikipedia2vec/wikipedia2vec#27]
I think the embedding of token '\n' is almost useless, and it will cause some IO errors when we load embedding in the specific operate system, which use the '\n' as the line break symbol.

This problem exists when I use `torchtext` and `gensim`.

If it's my fault, how could I solve it elegantly? I solve it by deleting token '\n' and its embedding.

**Comment by ikuyamada** [comment]
Thank you for reporting the issue.
It would be appreciated if you let me know how to reproduce the problem (i.e., the platform, input file and code).
Also, I think it is a good practice to remove the *\n* token from the embedding if necessary.

**Comment by cloudyyyyy** [comment]
@ikuyamada 
For all I know, Mac OS X and Unix use '\n' as the line separator. Because many framework use the original python API `f.readline()` when loading embedding, it can't diff '\n' from token between line separator.

You can just reproduce this just use `torchtext`:

```python
from torchtext.vocab import Vectors
vectors = Vectors(name='/path/to/embedding')
```

I try this on zhwiki and enwiki embedding, but I think it's possible that all the file which format is text have the same problem.

**Comment by ikuyamada** [comment]
Thank you for your reply!
However, I successfully loaded the embedding file using torchtext without any issues.
```
from torchtext.vocab import Vectors
vectors = Vectors(name='enwiki_20180420_100d.txt')
```
I uncompressed the [English 100d pretrained embedding file](https://wikipedia2vec.github.io/wikipedia2vec/pretrained/#english) and used it as the input to torchtext.

Would you please specify the embedding file that you used as an input to torchtext?

**Comment by cloudyyyyy** [comment]
@ikuyamada 
Sorry for my fault. I test the `zhwiki_100d` and `enwiki_100d` embedding file once again, and only find the problem in the `zhwiki_100d` embedding. 

And the error log is:
```
  0%|          | 0/1572707 [00:00<?, ?it/s]Skipping token b'1572706' with 1-dimensional vector [b'100']; likely a header
  1%|          | 19354/1572707 [00:01<01:37, 15896.35it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-1797ce84b55e> in <module>
      2 
      3 embedding_path = '/Users/wangbicong/Downloads/zhwiki_20180420_100d.txt.bak'
----> 4 vectors = Vectors(embedding_path)

~/miniconda3/lib/python3.6/site-packages/torchtext/vocab.py in __init__(self, name, cache, url, unk_init, max_vectors)
    278         self.dim = None
    279         self.unk_init = torch.Tensor.zero_ if unk_init is None else unk_init
--> 280         self.cache(name, cache, url=url, max_vectors=max_vectors)
    281 
    282     def __getitem__(self, token):

~/miniconda3/lib/python3.6/site-packages/torchtext/vocab.py in cache(self, name, cache, url, max_vectors)
    359                             "read vectors have {} dimensions. All vectors must have "
    360                             "the same number of dimensions.".format(word, len(entries),
--> 361                                                                     dim))
    362 
    363                     try:

RuntimeError: Vector for token b'' has 0 dimensions, but previously read vectors have 100 dimensions. All vectors must have the same number of dimensions.
```

And you could find the reason in `torchtext/vocab.py' (version 0.3.1):
```
                for line in tqdm(f, total=num_lines):
                    # Explicitly splitting on " " is important, so we don't
                    # get rid of Unicode non-breaking spaces in the vectors.
                    entries = line.rstrip().split(b" ")

                    word, entries = entries[0], entries[1:]
                    if dim is None and len(entries) > 1:
                        dim = len(entries)
                    elif len(entries) == 1:
                        logger.warning("Skipping token {} with 1-dimensional "
                                       "vector {}; likely a header".format(word, entries))
                        continue
                    elif dim != len(entries):
                        raise RuntimeError(
                            "Vector for token {} has {} dimensions, but previously "
                            "read vectors have {} dimensions. All vectors must have "
                            "the same number of dimensions.".format(word, len(entries),
                                                                    dim))
```

**Comment by ikuyamada** [comment]
Thank you for investigating the issue!
I confirmed that Chinese embeddings contain *\n* character because the current Jieba-based Chinese tokenizer outputs *\n* as words.
This is a bug and I will fix this in the next release.

**Comment by ikuyamada** [comment]
I fixed the code in the above commit.
I also fixed the Chinese pretrained embeddings manually by removing the line corresponding to "\n", so the [embedding files](https://wikipedia2vec.github.io/wikipedia2vec/pretrained/#chinese) should be loaded from torchtext.

**Comment by cloudyyyyy** [comment]
Thanks for your work !
