### ISSUE TITLE
Where are the anchor context model words?

### ISSUE THREAD

**Issue by andrejzg** [wikipedia2vec/wikipedia2vec#28]
Do you know where the anchor context model words can be found?

Put otherwise, is there any way of extracting: 

_<(anchor link/entity), context text>_

**Comment by ikuyamada** [comment]
Wikipedia2Vec obtains contextual words for each link by directly reading Wikipedia from the DB.
The corresponding code can be found here:
https://github.com/wikipedia2vec/wikipedia2vec/blob/master/wikipedia2vec/wikipedia2vec.pyx#L630
Further, the DB can be built using the *build_dump_db* command.
