### ISSUE TITLE
How to extract entities from text using Wikipedia2Vec

### ISSUE THREAD

**Issue by iknoorjobs** [wikipedia2vec/wikipedia2vec#29]
Is there any way I can know the vocabulary of the pretrained model? Like in case of Word2Vec.

**Comment by ikuyamada** [comment]
You can obtain the list of entities by calling `entities()` method of the dictionary instance.
```
from wikipedia2vec import Wikipedia2Vec
model = Wikipedia2Vec.load(MODEL_FILE)
list(model.dictionary.entities())
```

**Comment by iknoorjobs** [comment]
Okay, thanks a lot.
And is there any way to extract entities from text dataset?
