### ISSUE TITLE
Entity Extraction using Wikipedia2Vec

### ISSUE THREAD

**Issue by iknoorjobs** [wikipedia2vec/wikipedia2vec#31]
Is there any way we can extract all the wikipedia entities from the text using Wikipedia2Vec? Or is there any other way to do the same. Kindly have a look on the example given below.

Example: 
Text      : "Scarlett Johansson is an American actress."
Entities : [ 'Scarlett Johansson' , 'American' ]

NOTE : I want to do it in Python

Thanks

**Comment by ikuyamada** [comment]
This repository does not contain code for entity extraction (or linking). Similar issue can be found at: https://github.com/wikipedia2vec/wikipedia2vec/issues/29.
