### ISSUE TITLE
Command not found after installation

### ISSUE THREAD

**Issue by pwecar** [wikipedia2vec/wikipedia2vec#33]
I installed the project via pip install --user wikipedia2vec and it works well on the python side. (for instance, I tried typing import wikipedia2vec on python and bingo)
However, when I tried typing "wikipedia2vec train enwiki.xml.bz2 model_file" on my bash, it just kept prompting "command not found". I wonder how to run those "train" "build_dictionary" and "train_embedding" commands after installation via pip. Thanks.

**Comment by ikuyamada** [comment]
Please refer to the following article:
https://stackoverflow.com/questions/46973667/python-console-scripts-doesnt-work-when-pip-install-user
