### ISSUE TITLE
Loading pretrained model failed 

### ISSUE THREAD

**Issue by MathildaSu** [wikipedia2vec/wikipedia2vec#34]
Hi, when I tried to load the pretrained model using the following command: 
```
wiki2vec = Wikipedia2Vec.load("enwiki_20180420_win10_500d.txt.bz2")
/
```
I got the following error: 

```
users/anaconda3/lib/python3.6/contextlib.py:81: UserWarning: mmap_mode "c" is not compatible with compressed file /users/grad/ting/tr.ting/OIE/KBE/enwiki_20180420_win10_500d.txt.bz2. "c" flag will be ignored.
  return next(self.gen)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wikipedia2vec/wikipedia2vec.pyx", line 172, in wikipedia2vec.wikipedia2vec.Wikipedia2Vec.load
  File "/user/anaconda3/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/users/grad/ting/tr.ting/anaconda3/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/users/grad/ting/tr.ting/anaconda3/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 52
```

Do you know the reason?

Thanks.

**Comment by ikuyamada** [comment]
`Wikipedia2Vec.load` method requires the *binary* format of the pretrained model. You need to download it from the following page:
https://wikipedia2vec.github.io/wikipedia2vec/pretrained/
Furthermore, it is also required to decompress the file.

**Comment by MathildaSu** [comment]
Hi, I tried decompressed as well, but got the same error.

**Comment by ikuyamada** [comment]
You need to download the binary version of the model file, and decompress the downloaded file.

**Comment by MathildaSu** [comment]
That’s exactly what I did

**Comment by ikuyamada** [comment]
Do you provide the code that can reproduce the error?

**Comment by MathildaSu** [comment]
wiki2vec = Wikipedia2Vec.load("enwiki_20180420_win10_500d.txt")
/

**Comment by ikuyamada** [comment]
As mentioned, you need to download the *binary* format.
