### ISSUE TITLE
wikipedia id other than title

### ISSUE THREAD

**Issue by EternalMoment** [wikipedia2vec/wikipedia2vec#35]
Hi team, great work! I have a quick question and hope you could help me out. 

I'm trying to match wikipedia2vec entity embedding to each annotation in TAC and CONLL dataset. To my understanding, the only way to lookup entity in wikipedia2vec is through Wikipedia entity page title. However, datasets are annotated through other ids such as:
1. wikipedia url: [https://en.wikipedia.org/wiki/Scarlett_Johansson](https://en.wikipedia.org/wiki/Scarlett_Johansson)
2. wikipedia page id: [20913246](https://en.wikipedia.org/w/index.php?title=Scarlett_Johansson&action=info)

or some other ids.

How do you convert between title and ids that these datasets use in the paper? 
For example, for id 1, do you use a util function that normalize url to the title in order to lookup wikipedia2vec entity embedding?

**Comment by ikuyamada** [comment]
You need to use Wikipedia titles to obtain entity embeddings.
Because Wikipedia titles are also unique, you do not need to use Wikipedia IDs.
You can obtain normalized Wikipedia titles from Wikipedia URLs simply by replacing underscores to whitespaces.

**Comment by EternalMoment** [comment]
Got it, thanks a lot for the response!

**Comment by EternalMoment** [comment]
@ikuyamada  quick question

After some examination of the code, the `Wikipedia2Vec.get_entity` method also resolve redirect if `resolve_redirect=True`.

`dump_db.resolve_redirect` looks up in a db and `Wikipedia2Vec.get_entity` looks up in a dictionary; do they differ in terms of lookup result?

**Comment by ikuyamada** [comment]
> dump_db.resolve_redirect looks up in a db and Wikipedia2Vec.get_entity looks up in a dictionary; do they differ in terms of lookup result?

They should be the same. `Dictionary` has a `redirect_dict` which is a copy of the redirect data stored in `DumpDB`.

See: https://github.com/wikipedia2vec/wikipedia2vec/blob/master/wikipedia2vec/dictionary.pyx#L245
