### ISSUE TITLE
suspicious / in title containing '

### ISSUE THREAD

**Issue by EternalMoment** [wikipedia2vec/wikipedia2vec#37]
Hey team,

This could be a silly question, but I found some wikipedia2vec titles with weird extra `\` in front of `'`

for example entity: [South Bird's Head languages](https://en.wikipedia.org/wiki/South_Bird%27s_Head_languages) has title`South Bird\'s Head languages` 

in a similar fassion:
```
Ch\'olan languages
Central Alaskan Yup\'ik language
Pa\'o language
...
```

I'm using python 3.6.8, it could be a encoding problem I think.

**Comment by EternalMoment** [comment]
After some further exam, there are actually two entity for `South Bird's Head languages`:
```
wikipedia2vec.get_entity("South Bird\'s Head languages") # with index 3532380
```
```
wikipedia2vec.get_entity("South Bird\\\'s Head languages") # with index 3532381
```

**Comment by ikuyamada** [comment]
It seems that these entities are added in the dictionary because they appear multiple times in the following page:
https://en.wikipedia.org/wiki/Module:Sandbox/KleptomaniacViolet/Language_families/Data/Trans%E2%80%93New_Guinea_languages/alpha/0
