### ISSUE TITLE
suspicious leading and trailing space in title

### ISSUE THREAD

**Issue by EternalMoment** [wikipedia2vec/wikipedia2vec#38]
Some wikipedia2vec entity titles has extra suspicious leading and trailing space. This issue includes some common entities such as [May](https://en.wikipedia.org/wiki/May) and [India](https://en.wikipedia.org/wiki/India)

```
wikipedia2vec.get_entity("India") # with index 2131751
wikipedia2vec.get_entity(" India") # with index 2011310
```
```
wikipedia2vec.get_entity("May") # with index 1938987
wikipedia2vec.get_entity(" May") # with index 2011219
```

**Comment by EternalMoment** [comment]
For trailing space there is an example:
`UCI Cyclo-cross World Championships` with index 3492053
`UCI Cyclo-cross World Championships ` with index 3829540

**Comment by ikuyamada** [comment]
Currently, Wikipedia2Vec simply takes all the links in Wikipedia, extracts and counts the entities that the links refer to, and adds entities to the dictionary if they appear greater than `min-entity-count` times. Therefore, if there are links pointing to " India" more than `min-entity-count` times, the entity is added in the dictionary. It is possible to include only *valid* entities, but I think it is better to include entities if they have no corresponding pages.
