### ISSUE TITLE
how can the result file saved by command save_text --format word2vec loaded by word2vec?

### ISSUE THREAD

**Issue by SnowPi** [wikipedia2vec/wikipedia2vec#40]
how can the result file saved by command save_text --format word2vec loaded by word2vec?

**Comment by SnowPi** [comment]
how to use this file?

**Comment by ikuyamada** [comment]
The format is compatible to the Word2vec format. Therefore, you can use the file using other libraries such as [Gensim](https://radimrehurek.com/gensim/models/keyedvectors.html#gensim.models.keyedvectors.Word2VecKeyedVectors.load_word2vec_format).
