### ISSUE TITLE
training the same model multiple times?

### ISSUE THREAD

**Issue by nickcastro** [wikipedia2vec/wikipedia2vec#43]
Thanks for releasing this. I have a question that I am hoping you can answer. If I were to train this model using one wikipedia dump, and then after training, consecutively train the same model on a new wikipedia dump, do you have any idea if good performance would be maintained? In other words, could this model be continually be trained on new wikipedia dumps indefinitely without losing quality of the embeddings?

https://en.wikipedia.org/wiki/Online_machine_learning

**Comment by ikuyamada** [comment]
Thank you for your insightful comments. I think performing re-training using a new Wikipedia dump based on a model trained with an older dump is generally a good idea though, Wikipedia2Vec does not currently support re-training based on a trained model.
