### ISSUE TITLE
Parsing disambiguation page

### ISSUE THREAD

**Issue by EternalMoment** [wikipedia2vec/wikipedia2vec#44]
The dump db has wrongly classified some pages regarding whether it's a disambiguation page.

For example:
`http://en.wikipedia.org/wiki/Ashta` is an entity in AIDA dataset

```
db.is_disambiguation("Ashta") => False
```
The `is_disambiguation` says it's not disambiguation page,
```
list(map(lambda p : p.text, db.get_paragraphs("Ashta"))) =>
<class 'list'>: ['Ashta,Madhya Pradesh may refer to:', 'Ashta, Bangladesh', 'Ashta, Madhya Pradesh, a municipality in Sehore district in the state of Madhya Pradesh, India', 'Ashta, Maharashtra, a city in Sangli district in the state of Maharashtra, India']
```
but the content is actually a disambiguation page.

I think it's due to how the page is parsed, [somewhere here](https://github.com/wikipedia2vec/wikipedia2vec/blob/cb7caee6fd1d55f11f4d58ee2e3a9af7b33a200a/wikipedia2vec/utils/wiki_page.pyx#L9)

**Comment by ikuyamada** [comment]
Thank you for reporting the issue.
*Ashta* should be recognized as disambiguation page now.
