### ISSUE TITLE
What Japanese text pre-processing method is used?

### ISSUE THREAD

**Issue by emadg** [wikipedia2vec/wikipedia2vec#46]
Hi,

Thanks for your great repository and providing pre-trained models. 

I want to use the JA pre-trained embeddings. I want to know what method of pre-processing the Wikipedia text (language-agnostic preprocessing & Japanese preprocessing) is used?

Knowing the word segmentation method is very important for me. Was MeCab used? If yes, which version of Mecab? Also, the dictionary and its version which is used in the word-segmenter program?

Thanks

**Comment by ikuyamada** [comment]
Hi, 
We used MeCab with the standard IPADIC dictionary.
The implementation of the tokenizer can be found [here](https://github.com/wikipedia2vec/wikipedia2vec/blob/master/wikipedia2vec/utils/tokenizer/mecab_tokenizer.pyx).
Further, we did not use any preprocessing except lowercasing.
I think the version of MeCab was 0.98.
