### ISSUE TITLE
Cant not download the Chinese pretrained model for 300-dim text model.

### ISSUE THREAD

**Issue by Lavine24** [wikipedia2vec/wikipedia2vec#47]
Can anyone download the Chinese pretrainrd model for 300-dim text model? http://wikipedia2vec.s3.amazonaws.com/models/zh/2018-04-20/zhwiki_20180420_300d.txt.bz2

**Comment by ikuyamada** [comment]
The permission of the file was not configured properly.
The file can be downloaded from the URL now.

**Comment by Lavine24** [comment]
> The permission of the file was not configured properly.
> The file can be downloaded from the URL now.

Solved it by using “axel”, Thank you very much.
