### ISSUE TITLE
can not build dump database

### ISSUE THREAD

**Issue by Lavine24** [wikipedia2vec/wikipedia2vec#49]
when I use the commond "wikipedia2vec build-dump-db DUMP_FILE OUT_FILE", I got some errors.
![image](https://user-images.githubusercontent.com/31796893/68765711-659e8e00-0658-11ea-94fa-4ffae300c260.png)

**Comment by ikuyamada** [comment]
I have never seen this error before, but this error is raised by the [lmdb library](https://lmdb.readthedocs.io/en/release/) which is used internally by Wikipedia2Vec.
Did you run multiple programs that write to the same DB?

**Comment by Lavine24** [comment]
> I have never seen this error before, but this error is raised by the [lmdb library](https://lmdb.readthedocs.io/en/release/) which is used internally by Wikipedia2Vec.
> Did you run multiple programs that write to the same DB?

No, I haven't run another programs in my machine. Could you please tell me what's version is stable for us to run? I try to change the version, but not suit for me, Thank you very much.

**Comment by ikuyamada** [comment]
The latest version of Wikipedia2Vec is stable, and the version of the LMDB library in my local machine is 0.94.
Also, what kind of storage and file system do you use to store the DB?
Because this issue is raised from LMDB, the library may have some issue on your environment.

**Comment by Lavine24** [comment]
> The latest version of Wikipedia2Vec is stable, and the version of the LMDB library in my local machine is 0.94.
> Also, what kind of storage and file system do you use to store the DB?
> Because this issue is raised from LMDB, the library may have some issue on your environment.

Thank you very much. It is the enviroment problem in my machine.
