### ISSUE TITLE
Availability Wiki dump 20-04-2018 (dd-mm-yyyy)

### ISSUE THREAD

**Issue by mickvanhulst** [wikipedia2vec/wikipedia2vec#50]
Hi,

For my project, I would like to use the pre-trained embeddings that are available on your Github [0]. However, I would then also need to have access to the original dump for the remainder of my project. The history of dumps for Wikimedia does not go back more than a few months, so I am curious if you still have this dump available and if you could share it?

Thanks in advance and for publically sharing the pre-trained embeddings :)!

[0] https://wikipedia2vec.github.io/wikipedia2vec/pretrained/

**Comment by ikuyamada** [comment]
Hi,

Thank you for your interest to our project. The dump file is available at the following URL:
https://wikipedia2vec.s3-ap-northeast-1.amazonaws.com/dumps/enwiki-20180420-pages-articles.xml.bz2

Please replace the language code in the dump file name to get dumps in other languages.
