### ISSUE TITLE
How to get most similar items to added/subtracted vectors?

### ISSUE THREAD

**Issue by youssefavx** [wikipedia2vec/wikipedia2vec#51]
I want to do something like this: 

`finalvec = wiki2vec.get_entity_vector("Scarlett Johansson") - wiki2vec.get_word_vector("american") + wiki2vec.get_word_vector("japanese")`

Or if that doesn't quite work, then: 

`finalvec = wiki2vec.get_entity_vector("Scarlett Johansson") + wiki2vec.get_entity_vector("George Clooney")`

And then: 

`mostsim = wiki2vec.most_similar(finalvec, 50)
`
I want to be able to add 2 vectors together or do mathematical operations in general then get the nearest entities to that vector. Is that possible? 

When I try it, I get this error: 

```
Traceback (most recent call last):
  File "wikipedia-finder2-withoutwhile.py", line 97, in <module>
    mostsim = wiki2vec.most_similar(finalvec, 50000)
TypeError: Argument 'item' has incorrect type (expected wikipedia2vec.dictionary.Item, got numpy.ndarray)
```

**Comment by ikuyamada** [comment]
The `Wikipedia2Vec` class has the `most_similar_by_vector()` method that returns the most similar items of a vector.
This can be implemented using `wiki2vec.most_similar_by_vector(finalvec, 50000)`.

**Comment by youssefavx** [comment]
Excellent, thank you so much!
