### ISSUE TITLE
Is it possible to do something like 'infer vector' given a document not in the data?

### ISSUE THREAD

**Issue by youssefavx** [wikipedia2vec/wikipedia2vec#53]
If I have my own document that is not in the data and I want to get the most similar Wiki pages / entities to that document, is that possible? 

I know that with Doc2Vec you can do something like 'infer vector' and then compare that vector to other entities. I'm looking for something similar perhaps, if it's possible.

**Comment by ikuyamada** [comment]
hank you for you interest to this software. You can compute the vector of a document by simply averaging the vectors of words contained in the document. The document vector should be placed close to the vectors of entities related to the document, so you can obtain the nearest neighbor entities over all entity vectors using cosine similarity.

**Comment by youssefavx** [comment]
Thanks so much for making it, it's amazing! 

I have a list of words which I'm iterating through and I can of course get each word's vector with: 

`wiki2vec.get_word_vector(word)`

However, I'm not sure how to:

1. Add the vectors 
2. Average all vectors 

I tried this: 

```
setofvectors = set([])
for word in listofwords:
    setofvectors.add(wiki2vec.get_word_vector(word))

```

But I am getting a KeyError. 

I'm not sure how to add all the vectors. 

I tried: 

```
finalvector = wiki2vec.get_word_vector(listofwords[0])
print(finalvector)
firstelement = True
for word in listofwords:
    if firstelement == True:
        firstelement = False
        continue
    
    finalvector = wiki2vec.get_word_vector(word) + finalvector
    

finalvector = finalvector / len(finalvector)
```

But that also gave me a KeyError: 

```
  File "w2v.py", line 177, in <module>
    finalvector = wiki2vec.get_word_vector(word) + finalvector
  File "wikipedia2vec/wikipedia2vec.pyx", line 105, in wikipedia2vec.wikipedia2vec.Wikipedia2Vec.get_word_vector
  File "wikipedia2vec/wikipedia2vec.pyx", line 110, in wikipedia2vec.wikipedia2vec.Wikipedia2Vec.get_word_vector
KeyError
```

**Comment by ikuyamada** [comment]
The KeyError means that the word does not exist in the vocabulary of Wikipedia2Vec.
Also, the vectors returned by Wikipedia2Vec are NumPy arrays, so please refer to the NumPy documentation for computing the average of multiple NumPy vectors.

**Comment by youssefavx** [comment]
Ah I see! 

Is there a specific numpy approach you'd recommend? I'm having a lot of trouble grouping the vectors into a list and then averaging them, even when looking at the docs (since I am a beginner to numpy)

I tried this: 
```
countofelements = 0
for word in listofwords:
    countofelements +=1.0
    if firstelement == True:
        firstelement = False
        continue
    #setofvectors.add(wiki2vec.get_word_vector(word))
    try:
        #finalvector = wiki2vec.get_word_vector(word.strip()) + finalvector
        finalvector = np.array(wiki2vec.get_word_vector(word.strip())) + np.array(finalvector)

    except KeyError:
        print(word, ' not in data')
        continue

finalvector = finalvector / float(len(finalvector))
print(finalvector)

mostsim = wiki2vec.most_similar_by_vector(finalvector, 50)

for ent in mostsim:
    print(ent[0], ent[1])
```

But the result I got was not accurate at all, it was in a different language and unrelated: 

```
<Word مونږ> 0.8654154
<Word کړه> 0.8616062
<Entity :Category:Wikipedia files on Wikimedia Commons> 0.8615501
<Entity Wikipedia:Naming conventions (common names)> 0.861241
<Word τελωνων> 0.860256
<Word انگلیسی> 0.85936505
<Word επιγινωσκει> 0.8587652
<Word ომე> 0.8578309
<Entity :Category:Ethnicity user templates> 0.85756916
<Word ጋዜጠኞች> 0.8556773
<Word خبره> 0.8556301
<Word شينوارے> 0.85427594
<Word کتابی> 0.85421836
<Word بيا> 0.8541437
<Word ﺧﻮﺏ> 0.8541146
<Word کولو> 0.8536401
<Entity :Category:Nationality user templates> 0.8525086
<Entity Milagros Fernández Ladra> 0.8522127
<Word انیمیشن> 0.85212356
<Entity Template:grading scheme> 0.85209066
<Word ځان> 0.851783
<Word ακουωσιν> 0.85170084
<Word دهغه> 0.85121274
<Word զարթնի> 0.85101277
<Word نوفمبر> 0.85067916
<Word زمونږ> 0.8505789
<Word طرزونه> 0.8504609
<Word ﻳﺎﺩ> 0.850289
<Word თა> 0.85019743
<Word ذلك> 0.85013044
<Word ﭤﻴﻮ> 0.8499903
<Word ლთა> 0.849762
<Word دومره> 0.8493798
<Word ﺳﻮ> 0.84897786
<Word موسيقۍ> 0.8486304
<Word ځکه> 0.8486039
<Word βασιλλεια> 0.8484057
<Word σταδιους> 0.8483096
<Word وې> 0.84830415
<Word γκελ> 0.84817123
<Word ددې> 0.84785044
<Word پوهيدو> 0.8478257
<Word ἀποκριθεὶς> 0.847544
<Word 콧노래를> 0.8471515
<Word 스텝을> 0.84714985
<Word کښې> 0.84659946
<Word دغه> 0.84618706
<Word მრ> 0.84588706
<Word ډير> 0.8458605
<Word 하여라> 0.84570736
```

**Comment by ikuyamada** [comment]
I think the results may be improved by applying some filtering to words (e.g., limiting only noun words or content words).
