### ISSUE TITLE
KeyError when trying get_entity_vector on some Wikipedia titles

### ISSUE THREAD

**Issue by katlap** [wikipedia2vec/wikipedia2vec#54]
I came across a number of Wikipedia titles, which I obtained from the last part of Wikipedia URLs,  that I couldn't get embeddings for using "get_entity_vector".  For example, I try model.get_entity_vector('New business development') or model.get_entity_vector(''Personal effectiveness") and I get KeyError. But the corresponding pages exist - https://en.wikipedia.org/wiki/New_business_development, https://en.wikipedia.org/wiki/Personal_effectiveness. 

Do you know why this could be happening? Thank you.

**Comment by ikuyamada** [comment]
Wikipedia2Vec learns embeddings using Wiikipedia links. Rare entities which are referred from the links less than *min-entity-count* times are not included in the vocabulary.
