### ISSUE TITLE
Code for Named Entity Disambiguation

### ISSUE THREAD

**Issue by vardaan123** [wikipedia2vec/wikipedia2vec#55]
Hi, is the code for the paper "Joint Learning of the Embedding of Words and Entities for Named Entity Disambiguation" which also learns the Wikipedia embedding using the anchor context model available? Or do you plan to release it sometime? I am particularly interested in NED model experiments.

Thanks

**Comment by ikuyamada** [comment]
Thank you for your interest to our paper!
Wikipedia2Vec implements the same model described in our CoNLL paper.
The code used for our NED experiments is not currently available, but it should be possible to achieve similar performance reported in the paper based on Wikipedia2Vec.
Also, the following recent studies also address the NED task based on Wikipedia2Vec:

* YELM: End-to-End Contextualized Entity Linking: https://arxiv.org/abs/1911.03834
* E-BERT: Efficient-Yet-Effective Entity Embeddings for BERT: https://arxiv.org/abs/1911.03681

**Comment by vardaan123** [comment]
Thanks for your response and the pointers!
