### ISSUE TITLE
How to add another tokenizer?

### ISSUE THREAD

**Issue by Kyubyong** [wikipedia2vec/wikipedia2vec#61]
Hi, thanks for this great repo!

I was wondering if I can add another tokenizer to Wikipedia2Vec. Currently, it takes some specific tokenizers such as mecab for Japanese and jieba for Chinese. But I'd like to test other tokenizers for other languages.

1. I tried to tweak the source code with `pip install -e .`, but it gave a complaint like `from dictionary import Dictionary
ImportError: No module named 'dictionary`. 
2. So instead I installed using `pip install wikipedia2vec`, and  added a `new_tokenizer.pyx` file in the utils/tokenizer folder. And I added it to the `__init__` file. But, the system failed to recognize it.

I'm not familar with cython. Would you help me with this?

**Comment by ikuyamada** [comment]
Hi,
Thank you for your interest to WIkipedia2Vec.
In addition to running `pip install -e .`, it is required to *cythonize* the code by installing Cython and running `cythonize.sh`.

**Comment by Kyubyong** [comment]
Thanks!!

**Comment by ikuyamada** [comment]
Feel free to ask questions if you experience any isssues
