### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by vivekkalyan** [wikipedia2vec/wikipedia2vec#63]
I am interested in this idea but would like to train on my custom dataset. Is there some format I could follow for the different intermediate files so that I can generate them myself but use this for the training. I would be happy to add a PR of being able to train custom datasets if that is interesting.

**Comment by ikuyamada** [comment]
Hi, 
Thanks for your interest in Wikipedia2Vec.
Wikipedia2Vec reads `DumpDB` while training the model, so you can train the model if you create the `DumpDB` based on your custom dataset.
`DumpDB` is created by parsing a Wikipedia dump using `mwparserfromhell` library: https://github.com/wikipedia2vec/wikipedia2vec/blob/master/wikipedia2vec/dump_db.pyx#L208

**Comment by vivekkalyan** [comment]
thanks, will look into it!
