### ISSUE TITLE
Error for training with --case-sensitive True

### ISSUE THREAD

**Issue by debraj135** [wikipedia2vec/wikipedia2vec#67]
Thank you for the great work on this!

Over [here](https://github.com/wikipedia2vec/wikipedia2vec/blob/b2712cfed5f266147d2358ee531da678601ada46/wikipedia2vec/mention_db.pyx#L115) when self._case_sensitive is True, the variable target_text remains uninitialized causing errors downstream. 

Is this behavior expected, and is there something that I am missing.

Thank you for any help on this!

**Comment by ikuyamada** [comment]
Thank you for raising the issue! This behavior is not expected. I will fix this and release a new version.

**Comment by ikuyamada** [comment]
I have released the new version of Wikipedia2Vec. The issue should be fixed now :)

**Comment by debraj135** [comment]
Appreciate the prompt response and fix, thank you!

**Comment by debraj135** [comment]
Are there any plans of extending this technique for embedding of words and entities to the union of Wikipedia as well as Wikidata? 

Are there existing methods that are already out there?

**Comment by ikuyamada** [comment]
Please let me know if you have any further issues.
Also, we do not currently have a plan to support Wikidata as a data source.
