### ISSUE TITLE
Hello all i am getting this unicode error surrogate thing. i m a new user and have no idea what this is. i use this code everything month and never had this issue before. plz help!!! this is a client deliverable and i am stressing!!!

### ISSUE THREAD

**Issue by skhurram3108** [wikipedia2vec/wikipedia2vec#73]
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-18-ef2ec94bae8a> in <module>
----> 1 pd.DataFrame(content).to_csv(f"first_scrape_{now}.csv")

c:\programdata\anaconda3\envs\aiib\lib\site-packages\pandas\core\generic.py in to_csv(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, decimal)
   3226             decimal=decimal,
   3227         )
-> 3228         formatter.save()
   3229 
   3230         if path_or_buf is None:

c:\programdata\anaconda3\envs\aiib\lib\site-packages\pandas\io\formats\csvs.py in save(self)
    200                 self.writer = UnicodeWriter(f, **writer_kwargs)
    201 
--> 202             self._save()
    203 
    204         finally:

c:\programdata\anaconda3\envs\aiib\lib\site-packages\pandas\io\formats\csvs.py in _save(self)
    322                 break
    323 
--> 324             self._save_chunk(start_i, end_i)
    325 
    326     def _save_chunk(self, start_i, end_i):

c:\programdata\anaconda3\envs\aiib\lib\site-packages\pandas\io\formats\csvs.py in _save_chunk(self, start_i, end_i)
    354         )
    355 
--> 356         libwriters.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)

pandas/_libs/writers.pyx in pandas._libs.writers.write_csv_rows()

UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1597-1598: surrogates not allowed

**Comment by ikuyamada** [comment]
It looks like

**Comment by ikuyamada** [comment]
The error seems unrelated to Wikipedia2Vec
